version: '3'
services:
  natrix:
    build: .
    restart: on-failure
    environment:
      PROJECT_NAME: /app/input/${PROJECT_NAME}
    volumes:
      - /srv/docker/natrix/database:/app/database
      - /srv/docker/natrix/results:/app/results
      - /srv/docker/natrix/input:/app/input
